language: go

matrix:
  include:
  - go: 1.8.7
  - go: 1.9.7
  - go: 1.10.4
  - go: 1.11

install:
  - # Do nothing.

script:
  - go get -t -v ./...
  - diff -u <(echo -n) <(gofmt -d -s .)
  - go vet ./...
