language: go

matrix:
  include:
  - go: 1.4.3
    env: GOVET=false
  - go: 1.5.4
    env: GOVET=true
  - go: 1.6.3
    env: GOVET=true
  - go: 1.7.3
    env: GOVET=true

install:
  - # Do nothing.

script:
  - go get -t -v ./...
  - diff -u <(echo -n) <(gofmt -d -s .)
  - if [ "$GOVET" = "true" ]; then go vet ./...; fi
